const CAMERA_COORDS_SPEED = 0.1;
const CAMERA_ANGLE_SPEED = 1;
const BIRD_Y = 0.01;
const BIRD_SPEED = 6;
const SLING_ELASTIC_Z_SCALING_SPEED = 0.002;
const SLING_ELASTIC_Y_SPEED = 0.05;


const GRAVITY = 0.9;

const TICK = 0.05;

const CHUCK_SPEED = 8;

const BIRD_RADIUS = 0.5;
const VERTICAL_PANE_BIG_RADIUS = 0.4;
const VERTICAL_PANE_SMALL_RADIUS = 0.1;
const HORIZONTAL_PANE_BIG_RADIUS = 0.8;
const HORIZONTAL_PANE_SMALL_RADIUS = 0.1;
const STRUCTURE_OBJ_RADIUS = 0.4;
const SMALLER_OBJ_RADIUS = 0.05;
const VERTICAL_ROCK_1_RADIUS = 0.4;
const HORIZONTAL_ROCK_1_RADIUS = 1.6;
const VERTICAL_ROCK_2_RADIUS = 0.75;
const HORIZONTAL_ROCK_2_RADIUS = 1.7;